#!/bin/bash

# Install option
if [ "$1" == "install" ]; then
	mkdir -p $HOME/.config/systemd/user
	cp -r /etc/skel/.config/systemd/user/* $HOME/.config/systemd/user/
	mkdir -p $HOME/.config/beepy-poll.d
	cp -r /etc/skel/.config/beepy-poll.d/* $HOME/.config/beepy-poll.d/

	for script in $HOME/.config/beepy-poll.d/*; do
		$script install
	done

	exit 0
fi

POLL_SCRIPT_DIR=$1
if [ -z "$POLL_SCRIPT_DIR" ]; then
	POLL_SCRIPT_DIR="$HOME/.config/beepy-poll.d"
fi

REWAKE_TIMER_PATH="/sys/firmware/beepy/rewake_timer"
REWAKE_INTERVAL=15

# Send SIG1 to exit and cancel repoll
cancel_repoll=0
handle_cancel_repoll() {
	echo "Canceling repoll"
	cancel_repoll=1
	echo 0 > $REWAKE_TIMER_PATH
}
trap handle_cancel_repoll INT TERM USR1

echo "beepy-poll $BASHPID started at $(date)"

if [ ! -d "$POLL_SCRIPT_DIR" ]; then
	echo "Poll script directory $POLL_SCRIPT_DIR not found"
	exit 0
fi

# Wait for NetworkManager
for i in $(seq 1 5); do
	echo "Waiting for NetworkManager... ($i/5)"
	if systemctl --quiet is-active NetworkManager; then
		break
	fi
	sleep 1
done

# Wait for network
for i in $(seq 1 5); do
	if [ "$cancel_repoll" -ne "0" ]; then
		exit 0
	fi

	echo "Waiting for network... ($i/5)"
	net_state=$(nmcli d show wlan0 | grep 'GENERAL.STATE:' | cut -d '(' -f 2 | tr -d ')')
	if [ "$net_state" == "connected" ]; then
		break
	fi
	sleep 1
done

if [ "$net_state" != "connected" ]; then
	echo "Network not found, repoll in $REWAKE_INTERVAL min."
	if [ "$cancel_repoll" -eq "0" ]; then
		echo $REWAKE_INTERVAL > $REWAKE_TIMER_PATH
	fi
	exit 0
fi

for script in $POLL_SCRIPT_DIR/*; do
	if [ "$cancel_repoll" -ne "0" ]; then
		exit 0
	fi

	echo "Running $script..."
	bash "$script" ||:
done

if [ "$cancel_repoll" -eq "0" ]; then
	echo "Polling done, repoll in $REWAKE_INTERVAL min."
	echo $REWAKE_INTERVAL > $REWAKE_TIMER_PATH
fi
