#!/bin/bash

set -e

# Check for old module
if modprobe -n sharp 2>/dev/null; then
	echo "error: please uninstall the old development sharp module"
	exit 1
fi

# Check for swap size on arm64
if [ "$(uname -m )" == "aarch64" ]; then
	. /etc/dphys-swapfile
	if (( CONF_SWAPSIZE < 512 )); then
		echo "error: CONF_SWAPSIZE detected as $CONF_SWAPSIZE"
		echo "Please edit /etc/dphys-swapfile, increase to at least 512, and reboot"
		exit 1
	fi
fi
