#!/bin/bash

if [ "$1" == "install" ]; then
	SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
	echo "Gomuks poller script installed to"
	echo "    $SCRIPTPATH/$(basename $0)"
	echo "You may need to edit it to set GOMUKS_ROOT"
	exit 0
fi

# Set path to transfered Gomuks directory
# export GOMUKS_ROOT=<path>
/usr/bin/gomuks --headless
